---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-app
spec:
  containers:
    - name: nginx-container
      image: nginx-image
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: host-volume
  volumes:
    - name: host-volume
      hostPath:
        path: /Users/jaisoft/Documents/MinikubeProjects/host-volumes
        type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: nginx-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
