apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
  - name: nginx-env
    image: nginx
    env:
    - name: SUPERSECRET
      valueFrom:
        secretKeyRef:
          name: supersecret
          key: secret

