apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-11-05T11:34:04Z"
  generation: 1
  labels:
    app: my-nginx2
  name: my-nginx2
  namespace: default
  resourceVersion: "13147"
  uid: 5393074c-10e1-4473-a14d-9520f55122c9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-nginx2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx2
    spec:
      containers:
      - image: nginx:1.15-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
