apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo
  type: NodePort
status:
  loadBalancer: {}
