apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-secret
  name: spring-secret
spec:
  containers:
    - image: spring-secrets:latest
      name: spring-secret
      ports:
        - containerPort: 8080
      imagePullPolicy: IfNotPresent
      env:      
        - name: SPRING_PROFILE
          value: dev
        - name: SPRING_APPLICATION_JSON
          valueFrom:
            configMapKeyRef:
              name: spring-config
              key: dev-config.json
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datasource-credentials
              key: password
  restartPolicy: Never  
                  
          
                
