---
apiVersion: v1
kind: Service
metadata:
  name: spring-configmap
spec:
  selector:
    app: spring-configmap
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-configmap
spec:
  selector:
    matchLabels:
      app: spring-configmap
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-configmap
    spec:
      containers:
        - name: spring-configmap
          image: spring-configmap:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
          # Define the environment variable
           - name: my.system.property
             valueFrom:
               configMapKeyRef:
                # The ConfigMap containing the value you want to assign to my.system.property
                 name: app-config
                # Specify the key associated with the value
                 key: my.system.property