apiVersion: v1
kind: Pod
metadata:
  name: web1
spec:
  containers:
  - name: front1
    image: httpd:latest
    ports:
      - containerPort: 80

  - name: back1
    image: ubuntu:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo hello; sleep 10; done"]
